# Generated by Django 3.1 on 2020-08-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='discipline',
        ),
        migrations.AddField(
            model_name='student',
            name='discipline',
            field=models.ManyToManyField(to='classes.Discipline'),
        ),
    ]
